name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Default DNA Samples
      id: default-dna-samples
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Default DNA Samples
        setup-command: ''
        command: javac src/Main.java && java -cp src Main
        input: ''
        expected-output: |-
          Reconstructed Sequence: GATCCTA
          Mutation found at index: 2
        comparison-method: contains
        timeout: 2
        max-score: 50
    - name: Handles Missing Target (-1)
      id: handles-missing-target-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Handles Missing Target (-1)
        setup-command: sed -i 's/String targetMutation = .*/String targetMutation
          = "NON-EXISTENT";/' src/Main.java && sed -i 's/String\[\] fragments = .*/String\[\]
          fragments = {"A", "A", "A"};/' src/Main.java
        command: javac src/Main.java && java -cp src Main
        input: ''
        expected-output: |-
          Reconstructed Sequence: AAA
          Mutation found at index: -1
        comparison-method: contains
        timeout: 2
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DEFAULT-DNA-SAMPLES_RESULTS: "${{steps.default-dna-samples.outputs.result}}"
        HANDLES-MISSING-TARGET-1_RESULTS: "${{steps.handles-missing-target-1.outputs.result}}"
      with:
        runners: default-dna-samples,handles-missing-target-1
